### ISSUE TITLE
U1 Revisar estructura visual

### ISSUE THREAD

**Issue by jdramirezl** [Vivi-Hoyos2710/DroneEcommerce#51]
- Que todas las vistas de la aplicación manejen la misma estructura visual. 
- Que se utilicen los mismos colores, fondos, tipos de letra, etc.

**Comment by Pokloskaya** [comment]
Todas las vistas de usuario tienen su estructura, y lo mismo pasa con todas las del admin.

**Comment by jdramirezl** [comment]
LGTM, como reviso @Pokloskaya todo esta en orden
