### ISSUE TITLE
f14 interfaces

### ISSUE THREAD

**Issue by jdramirezl** [Vivi-Hoyos2710/DroneEcommerce#65]
• Implemente una inversión de dependencias. Debe existir una interfaz y dos clases concretas. Sugerencias de inversiones de dependencias:

• Ej: imagen con GCP y local
• Ej: restar dinero de cuenta o mostrar imagen de cheque

**Comment by Pokloskaya** [comment]
Hicimos inversión de dependencias para la funcionalidad de subir imagen del producto.
